config/routes.rb
Rails.application.routes.draw do
	resources :game do
  		member do
    		get 'start'
    		get 'next'
    		get 'next_bad'
    	end
  	end
	get 'main/index'

  root 'game#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
	def finishGame
		self.winner = "Ничья"
		if (man_points > woman_points) 
			self.winner = man_name
		end
		if (woman_points > man_points) 
			self.winner = woman_name
		end
	end
end

app/models/mananalquestion.rb
class Mananalquestion < ApplicationRecord
end

app/models/manbdsmquestion.rb
class Manbdsmquestion < ApplicationRecord
end

app/models/manelectroquestion.rb
class Manelectroquestion < ApplicationRecord
end

app/models/manfistquestion.rb
class Manfistquestion < ApplicationRecord
end

app/models/manoralquestion.rb
class Manoralquestion < ApplicationRecord
end

app/models/manpiequestion.rb
class Manpiequestion < ApplicationRecord
end

app/models/manquestion.rb
class Manquestion < ApplicationRecord
end

app/models/womananalquestion.rb
class Womananalquestion < ApplicationRecord
end

app/models/womanbdsmquestion.rb
class Womanbdsmquestion < ApplicationRecord
end

app/models/womanelectroquestion.rb
class Womanelectroquestion < ApplicationRecord
end

app/models/womanfistquestion.rb
class Womanfistquestion < ApplicationRecord
end

app/models/womanoralquestion.rb
class Womanoralquestion < ApplicationRecord
end

app/models/womanpiequestion.rb
class Womanpiequestion < ApplicationRecord
end

app/models/womanquestion.rb
class Womanquestion < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  	@games = Game.all
  end

  def new
  end

  def create
  	@game = Game.new(params.require(:game).permit(:man_name, :woman_name, :type, :m_oral, :m_anal, :m_bdsm, :m_fist, :m_pie, :m_electro, :w_oral, :w_anal, :w_bdsm, :w_fist, :w_pie, :w_electro, :g_vibrator, :g_anal_plug, :g_vibro_pule, :g_massager, :g_strapon, :g_bondage, :g_pump, :g_plet, :g_klyap, :g_electro, :g_vosk, :g_latex, :g_rashiritel))
 	@game.step = 1
  	@game.man_points = 0
  	@game.woman_points = 0
  	@game.type_of = 1
  	reset_session
  	session[:curr_points] = 0
  	session[:man] ||= [0]
  	session[:man_type] ||= [0]
  	session[:woman_type] ||= [0]
  	session[:woman] ||= [0]
  	(session[:man_type] ||= []) << 1 if @game.m_anal
  	(session[:man_type] ||= []) << 2 if @game.m_bdsm
  	(session[:man_type] ||= []) << 3 if @game.m_fist
  	(session[:man_type] ||= []) << 4 if @game.m_oral
  	(session[:man_type] ||= []) << 5 if @game.m_pie
  	(session[:woman_type] ||= []) << 1 if @game.w_anal
  	(session[:woman_type] ||= []) << 2 if @game.w_bdsm
  	(session[:woman_type] ||= []) << 3 if @game.w_fist
  	(session[:woman_type] ||= []) << 4 if @game.w_oral
  	(session[:woman_type] ||= []) << 5 if @game.w_pie
  	@game.save
  	redirect_to @game
  end

  def show
  	@game = Game.find(params[:id])
  end

  def start
  	@game = Game.find(params[:id])
  	@game.step = 1
  	@game.man_points = 0
  	@game.woman_points = 0
  	@game.type_of = 1
  	session[:curr_points] = 0
  	@game.save
  end

  def next
  	@game = Game.find(params[:id])
    @point = 10
    if @game.step < 30

      @point = 40 if @game.step == 29
      @point = 30 if @game.step > 19 && @game.step < 29
      @point = 20 if @game.step > 9 && @game.step < 19
      @point = 10 if @game.step < 9

  	  if @game.type_of == 1
  			@question = Manquestion.where("points = ? AND id NOT IN(?) AND type_of IN(?)", @point, session[:man], session[:man_type])
        	@question = @question[rand(@question.size)]
        	puts ">>>>>>>>>>>>>>>>>>>>>>Question type: #{@question.type_of}"
  			@game.type_of = 2
  			@game.woman_points += session[:curr_points]
  			(session[:man] ||= []) << @question.id
  	  else
  			@question = Womanquestion.where("points = ? AND id NOT IN(?) AND type_of IN(?)", @point, session[:woman], session[:woman_type])
        	@question = @question[rand(@question.size)]
        	puts ">>>>>>>>>>>>>>>>>>>>>>Question type: #{@question.type_of}"
  			@game.step = @game.step + 1
  			@game.type_of = 1
  			@game.man_points += session[:curr_points]
  			(session[:woman] ||= []) << @question.id
      end

  	  session[:curr_points] = @question.points
  	  puts "game type: #{@game.type_of} "
  	  @game.save
    else
      @winner = @game.finishGame
      render :finish
    end
  end

  def next_bad
    @game = Game.find(params[:id])
    @point = 10
    if @game.step < 30

      @point = 40 if @game.step == 29
      @point = 30 if @game.step > 19 && @game.step < 29
      @point = 20 if @game.step > 9 && @game.step < 19
      @point = 10 if @game.step < 9

      if @game.type_of == 1
      
        @question = Manquestion.where("points = ? AND id NOT IN(?) AND type_of IN(?)", @point, session[:man], session[:man_type])
        @question = @question[rand(@question.size)]
        @game.type_of = 2
        @game.woman_points += session[:curr_points]
        (session[:man] ||= []) << @question.id
      else
        @question = Womanquestion.where("points = ? AND id NOT IN(?) AND type_of IN(?)", @point, session[:woman], session[:woman_type])
        @question = @question[rand(@question.size)]
        @game.step = @game.step + 1
        @game.type_of = 1
        @game.man_points += session[:curr_points]
        (session[:woman] ||= []) << @question.id
      end

      session[:curr_points] = @question.points
      puts "game type: #{@game.type_of} "
      @game.save
      render :next
    else
      @winner = @game.finishGame
      render :finish
    end
  end




end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/game/finish.html.erb
<div class="row">
    <div class="col-md-3">
        <h2><%= @game.man_name %></h2>
        <p><%= @game.man_points %></p>
    </div>
    <div class="col-md-6">
        <h2>Игра завершена</h2>
        <p>Победитель: <%= @game.winner %></p>
    </div>
    <div class="col-md-3">
        <h2><%= @game.woman_name %></h2>
        <p><%= @game.woman_points %></p>
    </div>
</div>


<p>
  <strong>Step:</strong>
  <%= @game.step %>
</p>

app/views/game/index.html.erb
<h1>Listing games</h1>
 
<table>
  <tr>
    <th>Man name</th>
    <th>Woman name</th>
  </tr>
 
  <% @games.each do |game| %>
    <tr>
      <td><%= game.man_name %></td>
      <td><%= game.woman_name %></td>
      <td><%= link_to 'Show', game_index_path(game) %></td>
    </tr>
  <% end %>
</table>

app/views/game/new.html.erb
<h1>Создаем новую игру</h1>
<%= form_for :game, url: game_index_path do |f| %>
<div class="form-group">
<div class="row">
    <div class="col-md-3">
        <%= f.label "Имя парня:" %><br>
    <%= f.text_field :man_name , class: "form-control"  %>
    <p><%= f.label "Приемлемо" %></p>
    <%= f.check_box :m_oral, as: :boolean, input_html: { checked: true }  %> <%= f.label "Оральные ласки" %><br>
    <%= f.check_box :m_anal, as: :boolean, input_html: { checked: true }  %> <%= f.label "Анальные ласки" %><br>
    <%= f.check_box :m_bdsm, as: :boolean, input_html: { checked: true }  %> <%= f.label "BDSM" %><br>
    <%= f.check_box :m_fist, as: :boolean, input_html: { checked: true }  %> <%= f.label "Фистинг" %><br>
    <%= f.check_box :m_pie, as: :boolean, input_html: { checked: true }  %> <%= f.label "Pissing" %><br>
    <%= f.check_box :m_electro, as: :boolean, input_html: { checked: true }  %> <%= f.label "Electro" %><br>
    </div>
    <div class="col-md-6">
    <%= f.label "Выберите тип игры" %><br>
    <%= f.select :type_of, options_for_select([["Легкая", "1"], ["Средняя", "2"], ["Тяжелая", "3"]]), {class: "form-control"} %><br><br>
    <p><%= f.label "Имеющиеся игрушки" %></p>
    <%= f.check_box :g_vibrator, as: :boolean, input_html: { checked: true }  %> <%= f.label "Вибратор" %><br>
    <%= f.check_box :g_anal_plug, as: :boolean, input_html: { checked: true }  %> <%= f.label "Анальная пробка" %><br>
    <%= f.check_box :g_vibro_pule, as: :boolean, input_html: { checked: true }  %> <%= f.label "Вибропуля" %><br>
    <%= f.check_box :g_massager, as: :boolean, input_html: { checked: true }  %> <%= f.label "Массажер" %><br>
    <%= f.check_box :g_strapon, as: :boolean, input_html: { checked: true }  %> <%= f.label "Страпон" %><br>
    <%= f.check_box :g_bondage, as: :boolean, input_html: { checked: true }  %> <%= f.label "Бондаж" %><br>
    <%= f.check_box :g_pump, as: :boolean, input_html: { checked: true }  %> <%= f.label "Помпа" %><br>
    <%= f.check_box :g_plet, as: :boolean, input_html: { checked: true }  %> <%= f.label "Плеть" %><br>
    <%= f.check_box :g_klyap, as: :boolean, input_html: { checked: true }  %> <%= f.label "Кляп" %><br>
    <%= f.check_box :g_electro, as: :boolean, input_html: { checked: true }  %> <%= f.label "Эллектро" %><br>
    <%= f.check_box :g_vosk, as: :boolean, input_html: { checked: true }  %> <%= f.label "Воск" %><br>
    <%= f.check_box :g_latex, as: :boolean, input_html: { checked: true }  %> <%= f.label "Латекс" %><br>
    <%= f.check_box :g_rashiritel, as: :boolean, input_html: { checked: true }  %> <%= f.label "Расширитель" %><br>
    </div>
    <div class="col-md-3">
        <%= f.label "Имя девушки:" %><br>
    <%= f.text_field :woman_name , class: "form-control" %>
    <p><%= f.label "Приемлемо" %></p>
    <%= f.check_box :w_oral, as: :boolean, input_html: { checked: true }  %> <%= f.label "Оральные ласки" %><br>
    <%= f.check_box :w_anal, as: :boolean, input_html: { checked: true }  %> <%= f.label "Анальные ласки" %><br>
    <%= f.check_box :w_bdsm, as: :boolean, input_html: { checked: true }  %> <%= f.label "BDSM" %><br>
    <%= f.check_box :w_fist, as: :boolean, input_html: { checked: true }  %> <%= f.label "Фистинг" %><br>
    <%= f.check_box :w_pie, as: :boolean, input_html: { checked: true }  %> <%= f.label "Pissing" %><br>
    <%= f.check_box :w_electro, as: :boolean, input_html: { checked: true }  %> <%= f.label "Electro" %><br>
    </div>
</div>
<div class="row">
    <div class="col-md">
         <%= f.submit "Начать игру", class: "btn btn-success" %>
    </div>

</div>
</div>
<% end %>

app/views/game/next.html.erb
<div class="row">
    <div class="col-md-3">
        <h2><%= @game.man_name %></h2>
        <p><%= @game.man_points %></p>
    </div>
    <div class="col-md-6">
    <% if @game.type_of == 1 %>
        <h3>Действие выполняет: <%= @game.man_name %></h3>
    <% else %>
        <h3>Действие выполняет: <%= @game.woman_name %></h3>
    <% end %>

    <%= @question.question %>
    <p><%= @question.points %></p>
    </div>
    <div class="col-md-3">
        <h2><%= @game.woman_name %></h2>
        <p><%= @game.woman_points %></p>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
         <%= button_to 'Выполнено', next_game_path(@game), method: :get, class: "btn btn-success" %>
    </div>
    <div class="col-md-6">
        <%= button_to 'Невыполнено', next_bad_game_path(@game), method: :get, class: "btn btn-danger" %>
    </div>
</div>

<p>
  <strong>Step:</strong>
  <%= @game.step %>
</p>

app/views/game/next_bad.html.erb
<p>
  <strong>Step:</strong>
  <%= @game.step %>
</p>

<p>
  <strong>Man points:</strong>
  <%= @game.man_points %>
</p>

<p>
  <strong>Woman points:</strong>
  <%= @game.woman_points %>
</p>

<p>
  <strong>Man name:</strong>
  <%= @game.man_name %>
</p>
 
<p>
  <strong>Woman name:</strong>
  <%= @game.woman_name %>
</p>

<p>
  <%= button_to 'OK', next_game_path(@game), method: :get %> <%= button_to 'NOT OK', next_bad_game_path(@game), method: :get %>
  
</p>

app/views/game/show.html.erb
<div class="row">
    <div class="col-md-3">
        <h2><%= @game.man_name %></h2>
        <p><%= @game.man_points %></p>
    </div>
    <div class="col-md-6">
        <h2>Правила игры</h2>
        <p>1. Побеждает тот, кто наберет максимальное кол-во баллов. За каждое выполненное заданием вам прибоваляется определенное колличество баллов. Задания усложняются с каждым разом и кол-во очков за выполненные задания - увеличивается. Если игрок не выполняет задание - с него списываются очки.</p>

        <p>2. Во время игры вы можете использовать свои очки чтобы снять одежду с аппонента или, чтобы вернуть свою.</p>

        <p>3. По окончанию игры - победителю достанется определенный приз.</p>

        <h2>Тяжелый уровень</h2>

        <p>Внимание! Вы выбрали самый тяжелый уровень игры. В данном случае в заданиях и в используемых игрушках нет никаких ограничений. Рекомендуем привести в порядок ваши сокровеные места, так как задания будут достаточно интимными и сложными для выполнения</p>

    </div>
    <div class="col-md-3">
        <h2><%= @game.woman_name %></h2>
        <p><%= @game.woman_points %></p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <%= button_to 'Принимаем', next_game_path(@game), method: :get, class: "btn btn-success"  %>
    </div>
</div>

app/views/game/start.html.erb
<div class="row">
    <div class="col-md-3">
        <h2><%= @game.man_name %></h2>
        <p><%= @game.man_points %></p>
    </div>
    <div class="col-md-6">
    Правила
    </div>
    <div class="col-md-3">
        <h2><%= @game.woman_name %></h2>
        <p><%= @game.woman_points %></p>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
         <%= button_to 'YFXFNM', next_game_path(@game), method: :get, class: "btn btn-success" %>
    </div>

</div>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>